### ISSUE TITLE
[BUG] Automatic updates in Ubuntu don't work

### ISSUE THREAD

**Issue by rinormaloku** [cjpais/Handy#400]
Hey there, love this project!

In Ubuntu (24.10), when you click on the Update Available in the status bar, it downloads the new version, and then nothing happens.

I restarted the app, but it doesn't make a difference. I have to download from the releases and manually install updates each time.

Not a big bummer, but just fyi

**Comment by gugerard** [comment]
Hi, Same here.

**Comment by cjpais** [comment]
Thanks for the reports, I think someone mentioned this in discord as well, but prefer to track here. It's possible it broke with some CI changes recently

**Comment by joshribakoff** [comment]
Also encountering the same issue, keeps downloading over and over but not installing / showing any error / taking any other action, as if it just downloads it and throws away the data.

**Comment by cjpais** [comment]
Hard to say, but it's possible the latest version will fix this. Please let me know @joshribakoff @gugerard @rinormaloku

**Comment by rinormaloku** [comment]
This is already fixed. Updated a few times successfully

**Comment by cjpais** [comment]
Thanks, closing

**Comment by mds08011** [comment]
Hey just wanted to report that I am still experiencing this same issue when upgrading from 0.7.8 to 0.7.9.  Clicking "Update Available" shows a download progress bar but does not install even after quitting and restarting the app.

My OS is PopOS (Ubuntu Based) and using the .deb release.

**Comment by mds08011** [comment]
I successfully upgraded from 0.7.9 to 0.7.10 through the .deb app.  This issue appears resolved to me.

**Comment by cjpais** [comment]
Great
